### ISSUE TITLE
lcd %:p:h fail in fugitive diff

### ISSUE THREAD

**Issue by tripurari001** [tomdaly/vim-statusline-generator#2]
Hi 
The function used to return git branch works fine in normal case 

but when I want to check the diff and do `:Gdiff` it shows a error 
<img width="844" alt="Screenshot 2019-04-23 at 5 02 19 PM" src="https://user-images.githubusercontent.com/17466642/56578163-9189f180-65ea-11e9-929c-4243634da978.png">

because `lcd %:p:h` dosen't work for something `fugitive:///Users/username/directory/.git//0/dirname/filename` type path

**Comment by tripurari001** [comment]
I think you may use `try-catch` there

**Comment by tripurari001** [comment]
something like 

```
function! StatuslineGitBranch()
  let b:gitbranch=""
  if &modifiable
    try
      lcd %:p:h
      let l:gitrevparse=system("git rev-parse --abbrev-ref HEAD")
      if l:gitrevparse!~"fatal: not a git repository"
        let b:gitbranch=' '.substitute(l:gitrevparse, '\n', '', 'g').' '
      endif
      lcd -
    catch
    endtry
    endif
  endfunction
```

**Comment by tomdaly** [comment]
Thanks for opening the issue! I've just fixed it with a try-catch block and improved the shell error parsing
